# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unfreeze_service/unfreeze_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unfreeze_service/unfreeze_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'unfreeze_service/unfreeze_service.proto\"\x1e\n\nAccountRef\x12\x10\n\x08receiver\x18\x01 \x01(\t\"\'\n\x06Status\x12\x0e\n\x06txHash\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2<\n\x0fUnfreezeService\x12)\n\x0fRequestUnfreeze\x12\x0b.AccountRef\x1a\x07.Status\"\x00\x62\x06proto3')
)




_ACCOUNTREF = _descriptor.Descriptor(
  name='AccountRef',
  full_name='AccountRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver', full_name='AccountRef.receiver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txHash', full_name='Status.txHash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='Status.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['AccountRef'] = _ACCOUNTREF
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountRef = _reflection.GeneratedProtocolMessageType('AccountRef', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTREF,
  '__module__' : 'unfreeze_service.unfreeze_service_pb2'
  # @@protoc_insertion_point(class_scope:AccountRef)
  })
_sym_db.RegisterMessage(AccountRef)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'unfreeze_service.unfreeze_service_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)



_UNFREEZESERVICE = _descriptor.ServiceDescriptor(
  name='UnfreezeService',
  full_name='UnfreezeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestUnfreeze',
    full_name='UnfreezeService.RequestUnfreeze',
    index=0,
    containing_service=None,
    input_type=_ACCOUNTREF,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNFREEZESERVICE)

DESCRIPTOR.services_by_name['UnfreezeService'] = _UNFREEZESERVICE

# @@protoc_insertion_point(module_scope)
