# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from bridge_operator import bridge_operator_pb2 as bridge__operator_dot_bridge__operator__pb2


class BridgeOperatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetEthAnchorSignature = channel.unary_unary(
        '/BridgeOperator/GetEthAnchorSignature',
        request_serializer=bridge__operator_dot_bridge__operator__pb2.EthAnchor.SerializeToString,
        response_deserializer=bridge__operator_dot_bridge__operator__pb2.EthApproval.FromString,
        )
    self.GetAergoAnchorSignature = channel.unary_unary(
        '/BridgeOperator/GetAergoAnchorSignature',
        request_serializer=bridge__operator_dot_bridge__operator__pb2.AergoAnchor.SerializeToString,
        response_deserializer=bridge__operator_dot_bridge__operator__pb2.AergoApproval.FromString,
        )


class BridgeOperatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetEthAnchorSignature(self, request, context):
    """Get signatures of anchoring messages from Ethereum
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAergoAnchorSignature(self, request, context):
    """Get signatures of anchoring messages from Aergo
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BridgeOperatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetEthAnchorSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetEthAnchorSignature,
          request_deserializer=bridge__operator_dot_bridge__operator__pb2.EthAnchor.FromString,
          response_serializer=bridge__operator_dot_bridge__operator__pb2.EthApproval.SerializeToString,
      ),
      'GetAergoAnchorSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetAergoAnchorSignature,
          request_deserializer=bridge__operator_dot_bridge__operator__pb2.AergoAnchor.FromString,
          response_serializer=bridge__operator_dot_bridge__operator__pb2.AergoApproval.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BridgeOperator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
