# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_operator/bridge_operator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bridge_operator/bridge_operator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%bridge_operator/bridge_operator.proto\"D\n\tEthAnchor\x12\x0c\n\x04root\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\t\x12\x19\n\x11\x64\x65stination_nonce\x18\x03 \x01(\t\":\n\x0b\x45thApproval\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0b\n\x03sig\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"F\n\x0b\x41\x65rgoAnchor\x12\x0c\n\x04root\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\x19\n\x11\x64\x65stination_nonce\x18\x03 \x01(\x04\"<\n\rAergoApproval\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0b\n\x03sig\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\x80\x01\n\x0e\x42ridgeOperator\x12\x33\n\x15GetEthAnchorSignature\x12\n.EthAnchor\x1a\x0c.EthApproval\"\x00\x12\x39\n\x17GetAergoAnchorSignature\x12\x0c.AergoAnchor\x1a\x0e.AergoApproval\"\x00\x62\x06proto3')
)




_ETHANCHOR = _descriptor.Descriptor(
  name='EthAnchor',
  full_name='EthAnchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='EthAnchor.root', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='EthAnchor.height', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='EthAnchor.destination_nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=109,
)


_ETHAPPROVAL = _descriptor.Descriptor(
  name='EthApproval',
  full_name='EthApproval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='EthApproval.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig', full_name='EthApproval.sig', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='EthApproval.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=169,
)


_AERGOANCHOR = _descriptor.Descriptor(
  name='AergoAnchor',
  full_name='AergoAnchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='AergoAnchor.root', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='AergoAnchor.height', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='AergoAnchor.destination_nonce', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=241,
)


_AERGOAPPROVAL = _descriptor.Descriptor(
  name='AergoApproval',
  full_name='AergoApproval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='AergoApproval.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig', full_name='AergoApproval.sig', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='AergoApproval.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=303,
)

DESCRIPTOR.message_types_by_name['EthAnchor'] = _ETHANCHOR
DESCRIPTOR.message_types_by_name['EthApproval'] = _ETHAPPROVAL
DESCRIPTOR.message_types_by_name['AergoAnchor'] = _AERGOANCHOR
DESCRIPTOR.message_types_by_name['AergoApproval'] = _AERGOAPPROVAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EthAnchor = _reflection.GeneratedProtocolMessageType('EthAnchor', (_message.Message,), dict(
  DESCRIPTOR = _ETHANCHOR,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:EthAnchor)
  ))
_sym_db.RegisterMessage(EthAnchor)

EthApproval = _reflection.GeneratedProtocolMessageType('EthApproval', (_message.Message,), dict(
  DESCRIPTOR = _ETHAPPROVAL,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:EthApproval)
  ))
_sym_db.RegisterMessage(EthApproval)

AergoAnchor = _reflection.GeneratedProtocolMessageType('AergoAnchor', (_message.Message,), dict(
  DESCRIPTOR = _AERGOANCHOR,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:AergoAnchor)
  ))
_sym_db.RegisterMessage(AergoAnchor)

AergoApproval = _reflection.GeneratedProtocolMessageType('AergoApproval', (_message.Message,), dict(
  DESCRIPTOR = _AERGOAPPROVAL,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:AergoApproval)
  ))
_sym_db.RegisterMessage(AergoApproval)



_BRIDGEOPERATOR = _descriptor.ServiceDescriptor(
  name='BridgeOperator',
  full_name='BridgeOperator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=306,
  serialized_end=434,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEthAnchorSignature',
    full_name='BridgeOperator.GetEthAnchorSignature',
    index=0,
    containing_service=None,
    input_type=_ETHANCHOR,
    output_type=_ETHAPPROVAL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAergoAnchorSignature',
    full_name='BridgeOperator.GetAergoAnchorSignature',
    index=1,
    containing_service=None,
    input_type=_AERGOANCHOR,
    output_type=_AERGOAPPROVAL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRIDGEOPERATOR)

DESCRIPTOR.services_by_name['BridgeOperator'] = _BRIDGEOPERATOR

# @@protoc_insertion_point(module_scope)
